.\"   Man page for the aqemu project.
.\"
.TH aqemu 1 "July 12, 2010" "v0.8.0"

.SH NAME
aqemu - Qt4 front-end to QEMU and KVM emulators

.SH SYNOPSIS
.B aqemu

.SH DESCRIPTION
AQEMU is a Qt4 graphical interface used to manage QEMU and KVM virtual \
machines.
It has user-friendly interface and allows to set up the majority of QEMU and \
KVM options.

.SH AUTHOR
Andrey Rijov <ANDron142@yandex.ru>
